In [2]:
import pandas as pd

In [3]:
book = pd.read_csv('books.csv')
tags = pd.read_csv('Bookstags.csv')
bookTags = pd.read_csv('book_tags.csv')

In [4]:
book

,id,book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,original_publication_year,original_title,...,ratings_count,work_ratings_count,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,image_url,small_image_url
0,1,2767052,2767052,2792775,272,439023483,9.780439e+12,Suzanne Collins,2008.0,The Hunger Games,...,4780653,4942365,155254,66715,127936,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...
1,2,3,3,4640799,491,439554934,9.780440e+12,"J.K. Rowling, Mary GrandPr√©",1997.0,Harry Potter and the Philosopher's Stone,...,4602479,4800065,75867,75504,101676,455024,1156318,3011543,https://images.gr-assets.com/books/1474154022m...,https://images.gr-assets.com/books/1474154022s...
2,3,41865,41865,3212258,226,316015849,9.780316e+12,Stephenie Meyer,2005.0,Twilight,...,3866839,3916824,95009,456191,436802,793319,875073,1355439,https://images.gr-assets.com/books/1361039443m...,https://images.gr-assets.com/books/1361039443s...
3,4,2657,2657,3275794,487,61120081,9.780061e+12,Harper Lee,1960.0,To Kill a Mockingbird,...,3198671,3340896,72586,60427,117415,446835,1001952,1714267,https://images.gr-assets.com/books/1361975680m...,https://images.gr-assets.com/books/1361975680s...
4,5,4671,4671,245494,1356,743273567,9.780743e+12,F. Scott Fitzgerald,1925.0,The Great Gatsby,...,2683664,2773745,51992,86236,197621,606158,936012,947718,https://images.gr-assets.com/books/1490528560m...,https://images.gr-assets.com/books/1490528560s...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,7130616,7130616,7392860,19,441019455,9.780441e+12,Ilona Andrews,2010.0,Bayou Moon,...,17204,18856,1180,105,575,3538,7860,6778,https://images.gr-assets.com/books/1307445460m...,https://images.gr-assets.com/books/1307445460s...
9996,9997,208324,208324,1084709,19,067973371X,9.780680e+12,Robert A. Caro,1990.0,Means of Ascent,...,12582,12952,395,303,551,1737,3389,6972,https://s.gr-assets.com/assets/nophoto/book/11...,https://s.gr-assets.com/assets/nophoto/book/50...
9997,9998,77431,77431,2393986,60,039330762X,9.780393e+12,Patrick O'Brian,1977.0,The Mauritius Command,...,9421,10733,374,11,111,1191,4240,5180,https://images.gr-assets.com/books/1455373531m...,https://images.gr-assets.com/books/1455373531s...
9998,9999,8565083,8565083,13433613,7,61711527,9.780062e+12,Peggy Orenstein,2011.0,Cinderella Ate My Daughter: Dispatches from th...,...,11279,11994,1988,275,1002,3765,4577,2375,https://images.gr-assets.com/books/1279214118m...,https://images.gr-assets.com/books/1279214118s...
9999,10000,8914,8914,11817,31,375700455,9.780376e+12,John Keegan,1998.0,The First World War,...,9162,9700,364,117,345,2031,4138,3069,https://images.gr-assets.com/books/1403194704m...,https://images.gr-assets.com/books/1403194704s...

In [5]:
tags

       tag_id    tag_name
0           0           -
1           1        --1-
2           2       --10-
3           3       --12-
4           4      --122-
...       ...         ...
34247   34247   Ôº£hildrens
34248   34248   Ôº¶ÔΩÅÔΩñÔΩèÔΩíÔΩâÔΩîÔΩÖÔΩì
34249   34249       Ôº≠ÔΩÅÔΩéÔΩáÔΩÅ
34250   34250      Ôº≥Ôº•Ôº≤Ôº©Ôº•Ôº≥
34251   34251  ÔΩÜÔΩÅÔΩñÔΩèÔΩïÔΩíÔΩâÔΩîÔΩÖÔΩì

[34252 rows x 2 columns]

In [6]:
bookTags

        goodreads_book_id  tag_id   count
0                       1   30574  167697
1                       1   11305   37174
2                       1   11557   34173
3                       1    8717   12986
4                       1   33114   12716
...                   ...     ...     ...
999907           33288638   21303       7
999908           33288638   17271       7
999909           33288638    1126       7
999910           33288638   11478       7
999911           33288638   27939       7

[999912 rows x 3 columns]

In [7]:
joint_tags=pd.merge(tags,bookTags,left_on='tag_id',right_on='tag_id',how='inner')

In [8]:
joint_tags['tag_name'] = joint_tags['tag_name'].str.lower().str.strip()

In [9]:
joint_tags

        tag_id    tag_name  goodreads_book_id  count
0            0           -                665      3
1            0           -              81176      5
2            0           -             147074      2
3            0           -            2983489      3
4            0           -            6713071      4
...        ...         ...                ...    ...
999907   34248   ÔΩÜÔΩÅÔΩñÔΩèÔΩíÔΩâÔΩîÔΩÖÔΩì            8520610    374
999908   34248   ÔΩÜÔΩÅÔΩñÔΩèÔΩíÔΩâÔΩîÔΩÖÔΩì            9361589   3765
999909   34249       ÔΩçÔΩÅÔΩéÔΩáÔΩÅ             248871    222
999910   34250      ÔΩìÔΩÖÔΩíÔΩâÔΩÖÔΩì              28866     24
999911   34251  ÔΩÜÔΩÅÔΩñÔΩèÔΩïÔΩíÔΩâÔΩîÔΩÖÔΩì            9361589    384

[999912 rows x 4 columns]

In [10]:
p = joint_tags.groupby('tag_name').count()
p = p.sort_values(by='count', ascending=False)

In [11]:
p

                   tag_id  goodreads_book_id  count
tag_name
to-read              9983               9983   9983
favorites            9881               9881   9881
owned                9858               9858   9858
books-i-own          9799               9799   9799
currently-reading    9776               9776   9776
...                   ...                ...    ...
lilac-girls             1                  1      1
likes                   1                  1      1
liked-it                1                  1      1
batman-new-52           1                  1      1
ÔΩìÔΩÖÔΩíÔΩâÔΩÖÔΩì                  1                  1      1

[34244 rows x 3 columns]

In [12]:
genres = ["Art", "Biography", "Business", "Chick Lit", "Children's", "Christian", "Classics", "Comics", "Contemporary", "Cookbooks", "Crime", "Ebooks", "Fantasy", "Fiction", "Gay and Lesbian", "Graphic Novels", "Historical Fiction", "History", "Horror", "Humor and Comedy", "Manga", "Memoir", "Music", "Mystery", "Nonfiction", "Paranormal", "Philosophy", "Poetry", "Psychology", "Religion", "Romance", "Science", "Science Fiction", "Self Help", "Suspense", "Spirituality", "Sports", "Thriller", "Travel", "Young Adult"]

In [13]:
genres = [genre.lower() for genre in genres]

In [14]:
new_tags = p[p.index.isin(genres)]

In [15]:
genres

['art',
 'biography',
 'business',
 'chick lit',
 "children's",
 'christian',
 'classics',
 'comics',
 'contemporary',
 'cookbooks',
 'crime',
 'ebooks',
 'fantasy',
 'fiction',
 'gay and lesbian',
 'graphic novels',
 'historical fiction',
 'history',
 'horror',
 'humor and comedy',
 'manga',
 'memoir',
 'music',
 'mystery',
 'nonfiction',
 'paranormal',
 'philosophy',
 'poetry',
 'psychology',
 'religion',
 'romance',
 'science',
 'science fiction',
 'self help',
 'suspense',
 'spirituality',
 'sports',
 'thriller',
 'travel',
 'young adult']

In [16]:
new_tags

              tag_id  goodreads_book_id  count
tag_name
fiction         9097               9097   9097
ebooks          7203               7203   7203
contemporary    5287               5287   5287
fantasy         4259               4259   4259
romance         4251               4251   4251
mystery         3686               3686   3686
classics        2785               2785   2785
thriller        2522               2522   2522
suspense        2419               2419   2419
history         2138               2138   2138
crime           2083               2083   2083
paranormal      1941               1941   1941
nonfiction      1833               1833   1833
horror          1372               1372   1372
science         1239               1239   1239
biography       1109               1109   1109
philosophy      1055               1055   1055
memoir           905                905    905
religion         893                893    893
psychology       810                810    810
spirituality     503                503    503
comics           469                469    469
travel           457                457    457
art              436                436    436
business         377                377    377
poetry           377                377    377
christian        357                357    357
music            226                226    226
sports           196                196    196
manga            196                196    196
cookbooks         92                 92     92

In [17]:
joint_tags['genre'] = joint_tags['tag_name'].apply(lambda x: x.lower() if x.lower() in genres else None)

In [18]:
joint_tags[joint_tags['genre'].notnull()]

        tag_id tag_name  goodreads_book_id  count   genre
87762     2938      art                 36     31     art
87763     2938      art                119     66     art
87764     2938      art                840     63     art
87765     2938      art                960     80     art
87766     2938      art                968    242     art
...        ...      ...                ...    ...     ...
940087   31155   travel           25489012    741  travel
940088   31155   travel           25817493      8  travel
940089   31155   travel           26583370      3  travel
940090   31155   travel           26722820      8  travel
940091   31155   travel           28187230     33  travel

[60573 rows x 5 columns]

In [19]:
fin=book.merge(joint_tags[joint_tags['genre'].notnull()], left_on='book_id', right_on="goodreads_book_id", how="inner")

In [20]:
fin

,id,book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,original_publication_year,original_title,...,ratings_3,ratings_4,ratings_5,image_url,small_image_url,tag_id,tag_name,goodreads_book_id,count,genre
0,1,2767052,2767052,2792775,272,439023483,9.780439e+12,Suzanne Collins,2008.0,The Hunger Games,...,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...,8055,contemporary,2767052,382,contemporary
1,1,2767052,2767052,2792775,272,439023483,9.780439e+12,Suzanne Collins,2008.0,The Hunger Games,...,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...,10210,ebooks,2767052,690,ebooks
2,1,2767052,2767052,2792775,272,439023483,9.780439e+12,Suzanne Collins,2008.0,The Hunger Games,...,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...,11305,fantasy,2767052,10836,fantasy
3,1,2767052,2767052,2792775,272,439023483,9.780439e+12,Suzanne Collins,2008.0,The Hunger Games,...,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...,11743,fiction,2767052,13819,fiction
4,1,2767052,2767052,2792775,272,439023483,9.780439e+12,Suzanne Collins,2008.0,The Hunger Games,...,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...,26138,romance,2767052,3341,romance
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60568,9999,8565083,8565083,13433613,7,61711527,9.780062e+12,Peggy Orenstein,2011.0,Cinderella Ate My Daughter: Dispatches from th...,...,3765,4577,2375,https://images.gr-assets.com/books/1279214118m...,https://images.gr-assets.com/books/1279214118s...,24526,psychology,8565083,94,psychology
60569,10000,8914,8914,11817,31,375700455,9.780376e+12,John Keegan,1998.0,The First World War,...,2031,4138,3069,https://images.gr-assets.com/books/1403194704m...,https://images.gr-assets.com/books/1403194704s...,4605,biography,8914,3,biography
60570,10000,8914,8914,11817,31,375700455,9.780376e+12,John Keegan,1998.0,The First World War,...,2031,4138,3069,https://images.gr-assets.com/books/1403194704m...,https://images.gr-assets.com/books/1403194704s...,10210,ebooks,8914,3,ebooks
60571,10000,8914,8914,11817,31,375700455,9.780376e+12,John Keegan,1998.0,The First World War,...,2031,4138,3069,https://images.gr-assets.com/books/1403194704m...,https://images.gr-assets.com/books/1403194704s...,14552,history,8914,776,history
60572,10000,8914,8914,11817,31,375700455,9.780376e+12,John Keegan,1998.0,The First World War,...,2031,4138,3069,https://images.gr-assets.com/books/1403194704m...,https://images.gr-assets.com/books/1403194704s...,21773,nonfiction,8914,64,nonfiction

In [21]:
duplicate_rows = fin[fin.duplicated(subset='book_id', keep=False)]
#joint_tags_no_duplicates = fin.drop_duplicates(subset='original_title', keep='first')

In [22]:
duplicate_rows

,id,book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,original_publication_year,original_title,...,ratings_3,ratings_4,ratings_5,image_url,small_image_url,tag_id,tag_name,goodreads_book_id,count,genre
0,1,2767052,2767052,2792775,272,439023483,9.780439e+12,Suzanne Collins,2008.0,The Hunger Games,...,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...,8055,contemporary,2767052,382,contemporary
1,1,2767052,2767052,2792775,272,439023483,9.780439e+12,Suzanne Collins,2008.0,The Hunger Games,...,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...,10210,ebooks,2767052,690,ebooks
2,1,2767052,2767052,2792775,272,439023483,9.780439e+12,Suzanne Collins,2008.0,The Hunger Games,...,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...,11305,fantasy,2767052,10836,fantasy
3,1,2767052,2767052,2792775,272,439023483,9.780439e+12,Suzanne Collins,2008.0,The Hunger Games,...,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...,11743,fiction,2767052,13819,fiction
4,1,2767052,2767052,2792775,272,439023483,9.780439e+12,Suzanne Collins,2008.0,The Hunger Games,...,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...,26138,romance,2767052,3341,romance
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60568,9999,8565083,8565083,13433613,7,61711527,9.780062e+12,Peggy Orenstein,2011.0,Cinderella Ate My Daughter: Dispatches from th...,...,3765,4577,2375,https://images.gr-assets.com/books/1279214118m...,https://images.gr-assets.com/books/1279214118s...,24526,psychology,8565083,94,psychology
60569,10000,8914,8914,11817,31,375700455,9.780376e+12,John Keegan,1998.0,The First World War,...,2031,4138,3069,https://images.gr-assets.com/books/1403194704m...,https://images.gr-assets.com/books/1403194704s...,4605,biography,8914,3,biography
60570,10000,8914,8914,11817,31,375700455,9.780376e+12,John Keegan,1998.0,The First World War,...,2031,4138,3069,https://images.gr-assets.com/books/1403194704m...,https://images.gr-assets.com/books/1403194704s...,10210,ebooks,8914,3,ebooks
60571,10000,8914,8914,11817,31,375700455,9.780376e+12,John Keegan,1998.0,The First World War,...,2031,4138,3069,https://images.gr-assets.com/books/1403194704m...,https://images.gr-assets.com/books/1403194704s...,14552,history,8914,776,history
60572,10000,8914,8914,11817,31,375700455,9.780376e+12,John Keegan,1998.0,The First World War,...,2031,4138,3069,https://images.gr-assets.com/books/1403194704m...,https://images.gr-assets.com/books/1403194704s...,21773,nonfiction,8914,64,nonfiction

In [23]:
fin['id'].dtype

dtype('int64')

In [24]:
fin['genres'] = [None] * len(fin)

In [25]:
count = 0
id_count = fin['id'].value_counts()

for i in range(1, 10001):
    genre = []
    
    for k in range(id_count.get(i, 0)):
        genre.append(fin.iloc[count]['genre'])
        count += 1
    
    fin.at[count-1, 'genres'] = genre

In [26]:
fin

,id,book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,original_publication_year,original_title,...,ratings_4,ratings_5,image_url,small_image_url,tag_id,tag_name,goodreads_book_id,count,genre,genres
0,1,2767052,2767052,2792775,272,439023483,9.780439e+12,Suzanne Collins,2008.0,The Hunger Games,...,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...,8055,contemporary,2767052,382,contemporary,None
1,1,2767052,2767052,2792775,272,439023483,9.780439e+12,Suzanne Collins,2008.0,The Hunger Games,...,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...,10210,ebooks,2767052,690,ebooks,None
2,1,2767052,2767052,2792775,272,439023483,9.780439e+12,Suzanne Collins,2008.0,The Hunger Games,...,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...,11305,fantasy,2767052,10836,fantasy,None
3,1,2767052,2767052,2792775,272,439023483,9.780439e+12,Suzanne Collins,2008.0,The Hunger Games,...,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...,11743,fiction,2767052,13819,fiction,None
4,1,2767052,2767052,2792775,272,439023483,9.780439e+12,Suzanne Collins,2008.0,The Hunger Games,...,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...,26138,romance,2767052,3341,romance,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60568,9999,8565083,8565083,13433613,7,61711527,9.780062e+12,Peggy Orenstein,2011.0,Cinderella Ate My Daughter: Dispatches from th...,...,4577,2375,https://images.gr-assets.com/books/1279214118m...,https://images.gr-assets.com/books/1279214118s...,24526,psychology,8565083,94,psychology,"[contemporary, ebooks, history, memoir, nonfic..."
60569,10000,8914,8914,11817,31,375700455,9.780376e+12,John Keegan,1998.0,The First World War,...,4138,3069,https://images.gr-assets.com/books/1403194704m...,https://images.gr-assets.com/books/1403194704s...,4605,biography,8914,3,biography,None
60570,10000,8914,8914,11817,31,375700455,9.780376e+12,John Keegan,1998.0,The First World War,...,4138,3069,https://images.gr-assets.com/books/1403194704m...,https://images.gr-assets.com/books/1403194704s...,10210,ebooks,8914,3,ebooks,None
60571,10000,8914,8914,11817,31,375700455,9.780376e+12,John Keegan,1998.0,The First World War,...,4138,3069,https://images.gr-assets.com/books/1403194704m...,https://images.gr-assets.com/books/1403194704s...,14552,history,8914,776,history,None
60572,10000,8914,8914,11817,31,375700455,9.780376e+12,John Keegan,1998.0,The First World War,...,4138,3069,https://images.gr-assets.com/books/1403194704m...,https://images.gr-assets.com/books/1403194704s...,21773,nonfiction,8914,64,nonfiction,"[biography, ebooks, history, nonfiction]"

In [27]:
duplicate_rows = fin.drop_duplicates(subset='original_title', keep='last')

In [28]:
duplicate_rows

,id,book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,original_publication_year,original_title,...,ratings_4,ratings_5,image_url,small_image_url,tag_id,tag_name,goodreads_book_id,count,genre,genres
6,1,2767052,2767052,2792775,272,439023483,9.780439e+12,Suzanne Collins,2008.0,The Hunger Games,...,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...,30358,thriller,2767052,800,thriller,"[contemporary, ebooks, fantasy, fiction, roman..."
12,2,3,3,4640799,491,439554934,9.780440e+12,"J.K. Rowling, Mary GrandPr√©",1997.0,Harry Potter and the Philosopher's Stone,...,1156318,3011543,https://images.gr-assets.com/books/1474154022m...,https://images.gr-assets.com/books/1474154022s...,22973,paranormal,3,923,paranormal,"[classics, contemporary, fantasy, fiction, mys..."
23,4,2657,2657,3275794,487,61120081,9.780061e+12,Harper Lee,1960.0,To Kill a Mockingbird,...,1001952,1714267,https://images.gr-assets.com/books/1361975680m...,https://images.gr-assets.com/books/1361975680s...,20939,mystery,2657,246,mystery,"[classics, contemporary, crime, fiction, histo..."
27,5,4671,4671,245494,1356,743273567,9.780743e+12,F. Scott Fitzgerald,1925.0,The Great Gatsby,...,936012,947718,https://images.gr-assets.com/books/1490528560m...,https://images.gr-assets.com/books/1490528560s...,26138,romance,4671,2090,romance,"[classics, ebooks, fiction, romance]"
31,6,11870085,11870085,16827462,226,525478817,9.780525e+12,John Green,2012.0,The Fault in Our Stars,...,698471,1311871,https://images.gr-assets.com/books/1360206420m...,https://images.gr-assets.com/books/1360206420s...,26138,romance,11870085,7849,romance,"[contemporary, ebooks, fiction, romance]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60554,9996,7130616,7130616,7392860,19,441019455,9.780441e+12,Ilona Andrews,2010.0,Bayou Moon,...,7860,6778,https://images.gr-assets.com/books/1307445460m...,https://images.gr-assets.com/books/1307445460s...,26138,romance,7130616,464,romance,"[contemporary, ebooks, fantasy, fiction, myste..."
60558,9997,208324,208324,1084709,19,067973371X,9.780680e+12,Robert A. Caro,1990.0,Means of Ascent,...,3389,6972,https://s.gr-assets.com/assets/nophoto/book/11...,https://s.gr-assets.com/assets/nophoto/book/50...,21773,nonfiction,208324,48,nonfiction,"[biography, classics, history, nonfiction]"
60562,9998,77431,77431,2393986,60,039330762X,9.780393e+12,Patrick O'Brian,1977.0,The Mauritius Command,...,4240,5180,https://images.gr-assets.com/books/1455373531m...,https://images.gr-assets.com/books/1455373531s...,14552,history,77431,36,history,"[classics, ebooks, fiction, history]"
60568,9999,8565083,8565083,13433613,7,61711527,9.780062e+12,Peggy Orenstein,2011.0,Cinderella Ate My Daughter: Dispatches from th...,...,4577,2375,https://images.gr-assets.com/books/1279214118m...,https://images.gr-assets.com/books/1279214118s...,24526,psychology,8565083,94,psychology,"[contemporary, ebooks, history, memoir, nonfic..."
60572,10000,8914,8914,11817,31,375700455,9.780376e+12,John Keegan,1998.0,The First World War,...,4138,3069,https://images.gr-assets.com/books/1403194704m...,https://images.gr-assets.com/books/1403194704s...,21773,nonfiction,8914,64,nonfiction,"[biography, ebooks, history, nonfiction]"

In [29]:
duplicate_rows.to_csv('books.csv',encoding='utf-8',index=False)